#pragma config(Sensor, dgtl3,  sonarSensor,    sensorSONAR_mm)
#pragma config(Sensor, dgtl6,  bumpsensor,     sensorTouch)
#pragma config(Sensor, dgtl7,  bumpsensor2,    sensorTouch)
#pragma config(Sensor, dgtl8,  test,           sensorTouch)
#pragma config(Sensor, dgtl9,  one,            sensorTouch)
#pragma config(Sensor, dgtl10, two,            sensorTouch)
#pragma config(Sensor, dgtl11, three,          sensorTouch)
#pragma config(Motor,  port2,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           ultServo,      tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int ServoMove(int servoPosition){

  //writeDebugStreamLine("Servo Position = %d",servoPosition);
  int ult = SensorValue(sonarSensor); //gets light sensor value
  //writeDebugStreamLine("POT = %d",SensorValue(POT));
  motor[ultServo] = servoPosition; //moves servo to current position
  wait1Msec(200);
  return ult;
}

task main(){
//motors 9 and 10

	string side = "left";
	string currentSide = "";
	ServoMove(120);
	//motor[rightMotor] = 40;
	//motor[leftMotor] = 50;
	//add get side
  motor[rightMotor] = -50; //forward
	motor[leftMotor] = -45;
	wait1Msec(200);
	bool b = true;
	while(b){ //robot moves forward

		int bumpSensor = SensorValue[bumpsensor];
		int bumpSensor2 = SensorValue[bumpsensor2];
		if (bumpSensor == 1 || bumpSensor2==1){ //if bump sensor is hit, stop
			motor[rightMotor] = 0;
			motor[leftMotor] = 0;
			wait1Msec(250);
			motor[rightMotor] = 30; //reverse
			motor[leftMotor] = 30;
			wait1Msec(500);
			motor[rightMotor] = 0; //rotate to the right
			motor[leftMotor] = -40;
			wait1Msec(1400);
			motor[rightMotor] = 0;
			motor[leftMotor] = 0;
			wait1Msec(250);
			}

		int ultSensor = SensorValue(sonarSensor);

		//if (currentSide != side){ //if there is no current side
	if (ultSensor > 150 || ultSensor == -1){
		  motor[rightMotor] = 0;
			motor[leftMotor] = 0;
			wait1Msec(500);
			if (bumpSensor == 1 || bumpSensor2==1){ //if bump sensor is hit, stop
		    	motor[rightMotor] = 0;
		 			motor[leftMotor] = 0;
					wait1Msec(250);
					motor[rightMotor] = 30; //reverse
					motor[leftMotor] = 30;
					wait1Msec(500);
					motor[rightMotor] = 0; //rotate to the right
					motor[leftMotor] = -40;
					wait1Msec(1400);
					motor[rightMotor] = 0;
					motor[leftMotor] = 0;
			    wait1Msec(250);
			  }
			else{
			motor[rightMotor] = -40;
			motor[leftMotor] = 30;
			wait1Msec(1200);
			while(ultSensor > 150 || ultSensor == -1){
				ultSensor = SensorValue(sonarSensor);
				bumpSensor = SensorValue[bumpsensor];
		    bumpSensor2 = SensorValue[bumpsensor2];
		    if (bumpSensor == 1 || bumpSensor2==1){ //if bump sensor is hit, stop
		    	motor[rightMotor] = 0;
		 			motor[leftMotor] = 0;
					wait1Msec(250);
					motor[rightMotor] = 30; //reverse
					motor[leftMotor] = 30;
					wait1Msec(500);
					motor[rightMotor] = 0; //rotate to the right
					motor[leftMotor] = -40;
					wait1Msec(1400);
					motor[rightMotor] = 0;
					motor[leftMotor] = 0;
					wait1Msec(250);
		    	break;
			  }
				motor[rightMotor] = -40;
				motor[leftMotor] = -30;       /////used to be -35
				wait1Msec(1);
			}
		}
			motor[rightMotor] = 0;
			motor[leftMotor] = 0;
			wait1Msec(500);
			//turn slightly into wall
			//motor[rightMotor] =
		}
		motor[rightMotor] = -50;
		motor[leftMotor] = -45;
		wait1Msec(200);

	}
}
